<?php
include_once('header.phtml');    
?>

<div class="container">
    <div class="row py-1" style="margin-top: 20px;">
        <div class="col-sm-5" style="text-align: center;margin-bottom: 20px;"><img src="/be/public/img/portfolio/me.jpg" style="border-radius: 50%;max-width:50%;" alt="Avatar"></div>
        <div class="col-sm-7">
                <h5>Tel: 086-996-0144</h5>
                <h5>Date of Birth: 06 June 1992</h5>
                <h5>Email:<a href="mailto:point.sopittha@gmail.com">point.sopittha@gmail.com</a></h5>
                <h5>Expected Salary: Negotiatble</h5>
                <h5>Able to work abroad: Yes</h5>
                <h5>Hobbies: <i class="fas fa-gamepad"></i> <i class="fas fa-microchip"></i>  <i class="fas fa-plane"></i>  <i class="fas fa-luggage-cart"></i>  <i class="fas fa-swimmer"></i>  <i class="fas fa-dumbbell"></i>  <i class="fas fa-utensils"></i></h5>
            </div>       
    </div>
        
    <hr/>
    <div class="row py-1">
        <div class="col-sm-4 col-md-4"><h4>CAREER OBJECTIVE</h4></div>
        <div class="col-sm-8 col-md-8"><p>To obtain a position relating to Software development Assistant Manager,
Software development Project Assistant Manager, Software Engineer, Software
Analyst and Software Developer</p></div>
    </div>
    <hr/>
    <div class="row py-1">
        <div class="col-sm-4 col-md-4"><h4>WORK EXPERIENCE <i class="fas fa-briefcase"></i></h4></div>
        <div class="col-sm-8 col-md-8"></div>
    </div>
    <div class="row py-1">
        <div class="col-sm-4 col-md-4">JULY 2017 - PRESENT</div>
        <div class="col-sm-8 col-md-8">
        <ul style="list-style-type: none;">
            <li><strong>Software development section manager</strong></li>
            <li><a href="https://www.cpli.co.th/page/" target="_blank">CP Leadership Institute</a>
                <ul>
                    <li>Transform offline business processes to online solution.</li>
                    <li>Review ,design, implement and customize both software and database design</li>
                    <li>In charge of software development projects management, coordinator outsourcing vendors</li>
                    <li>Contribute to all phases of the development life cycle</li>
                    <li>Summarized and reported directed to manager</li>
                </ul>
            </li>
            <li><strong>Responsible to projects</strong>
                <ul>
                    <li>Operation system</li>
                    <li>Online registration with APIs</li>
                    <li>Program and Participant management</li>
                    <li>Facilities management</li>
                    <li>360 evaluation forms and reports</li>
                    <li>Financial system and report (E-invoice)</li>
                </ul>
            </li>
        </ul>
        </div>
    </div>
    <div class="row py-1">
        <div class="col-sm-4 col-md-4">JULY 2015 – JULY 2017</div>
        <div class="col-sm-8 col-md-8">
        <ul style="list-style-type: none;">
            <li><strong>Software developer</strong></li>
            <li><a href="https://www.asiasoft.net/th-th/" target="_blank">Asiasoft Corporation Public Company Limited</a>
                <ul>
                    <li>Research ,develop and deliver software to support business and givenrequirements.</li>
                    <li>Review, analyze and modify existing parts of program, including encoding, testing, debugging and documentation.</li>
                    <li>Analyst system requirement or Analyst System improvement possibility.</li>
                    <li>Work with Technology team to design and build a maintainable technology infrastructure including build & testing environment.</li>
                    <li>Contribute to designing and building production systems on both web and mobile services.</li>
                    <li>Develop and perform test scenarios, test cases and test plan.</li>
                    <li>Perform work based on defined process and provide feedback on process improvements as appropriate.</li>
                </ul>
            </li>
            <li><strong>Responsible to projects</strong>
                <ul>
                    <li>Refill Payment Gateway (Top-up) connect with other merchants payment services (such as Line Pay, KBank, Paypal, Indomog, MogPay, Gudang Voucher, Modern pay and OpenBucks)</li>
                    <li><a href="https://secure3.playpark.com/refill/RefillCenterSystem/" target="_blank">Game Refill Center System</a></li>
                    <li><a href="https://akey.asiasoft.co.th/" target="_blank">@Key system (Login with Digipass System for game member and internal user)</a></li>
                    <li>Customer Relationship Management System (Internal Admin Tool)</li>
                    <li>Navision/Financial Report</li>
                    <li>Customer Tracking Report System</li>
                    <li>Game Events, Ads banner system</li>
                </ul>
            </li>
        </ul>     
        </div>
    </div>
     <hr/>
    <div class="row py-1">
        <div class="col-sm-4 col-md-4"><h4>EDUCATION <i class="fas fa-graduation-cap"></i></h4></div>
        <div class="col-sm-8 col-md-8"><h4></h4></div>
    </div>
    <div class="row py-1">
        <div class="col-sm-4 col-md-4">2011-2015</div>
        <div class="col-sm-8 col-md-8">
        <ul style="list-style-type: none;">
            <li><strong>Bachelor of Engineering in Computer Engineering</strong></li>
            <li>Dhurakij Pundit University</li>
          
        </ul>
        </div>
    </div>
    <div class="row py-1">
        <div class="col-sm-4 col-md-4">2007-2009</div>
        <div class="col-sm-8 col-md-8">
        <ul style="list-style-type: none;">
            <li><strong>Intensive English Program - High school, Science – Mathematics major</strong></li>
            <li>PotisarnPittayakorn School</li>
        </ul>
        </div>
    </div>
    <div class="row py-1">
        <div class="col-sm-4 col-md-4">2004-2007</div>
        <div class="col-sm-8 col-md-8">
        <ul style="list-style-type: none;">
            <li><strong>English Program - Junior high school, Science – Mathematics major</strong></li>
            <li>PotisarnPittayakorn School</li>
        </ul>
        </div>
    </div>
    <hr/>
    <div class="row py-1">
        <div class="col-sm-4 col-md-4"><h4>SKILLS <i class="fas fa-comment"></i></h4></div>
        <div class="col-sm-8 col-md-8"><ul style="list-style-type: none;">
            <li><strong>Platform / Software</strong>
                <ul>
                    <li>Windows & Linux Server</li>
                    <li>MSSQL Server , Oracle, MYSQL Server, XAMPP, MongoDB, redisDB</li>
                    <li>Microsoft Office applications (Word, Excel, PowerPoint, Visio, Projects,Publisher)</li>
                    <li>Microsoft Visual Studio, Xcode, Eclipse, Arduino IDE</li>
                    <li>Adobe Photoshop, Flash, Illustrator, Dreamweaver</li>
                    <li>SAP, Crystal Report</li>
                    <li>CASE tools, OOP methodology (UML), Design Pattern , MVC</li>
                    <li>Wordpress</li>
                </ul>
            </li>
            <li><strong>Framework</strong>
                <ul>
                    <li>Angular, Nodejs, ASP, ASP.NET (Web app, Web Service)</li>
                </ul>
            </li>
            <li><strong>Languages</strong>
                <ul>
                    <li>Java, C#, C, C++, PHP, SQL, HTML, CSS, ABAP</li>
                </ul>
            </li>
            <li><strong>Other</strong>
                <ul>
                    <li>Have a car driver’s license</li>
                </ul>
            </li>
        </ul></div>
    </div>
     <hr/>
    <div class="row py-1">
        <div class="col-sm-4 col-md-4"><h4>COURSE TRAINING <i class="fas fa-brain"></i></h4></div>
        <div class="col-sm-8 col-md-8">
        <ul>
            <li><strong><a href="http://www.swpark.or.th/index.php?option=com_training&view=course&id=93" target="_blank">Design technique for high performance system</a></strong></li>
            <li  style="list-style-type: none;">Software Park Thailand</li>
        </ul>
        </div>
    </div>
    <div class="row py-1">
        <div class="col-sm-4 col-md-4"></div>
        <div class="col-sm-8 col-md-8">
        <ul>
            <li><strong>Object-Oriented Analysis and Design with UML 2.0</strong></li>
            <li  style="list-style-type: none;">Iverson Training Center</li>
        </ul>
        </div>
    </div>
</div>


<?php
include_once('footer.phtml');
?>
