<?php
include_once('header.phtml');    
?>

<div class="container">
    <div class="row py-1">
        <div class="col-sm-4 col-md-3">CAREER OBJECTIVE</div>
        <div class="col-sm-8 col-md-9"><p>To obtain a position relating to Software development Assistant Manager,
Software development Project Assistant Manager, Software Engineer, Software
Analyst and Software Developer</p></div>
    </div>
    <hr/>
    <div class="row py-1">
        <div class="col-sm-4 col-md-3">WORK EXPERIENCE</div>
        <div class="col-sm-8 col-md-9"></div>
    </div>
    <div class="row py-1">
        <div class="col-sm-4 col-md-3">JULY 2017 - PRESENT</div>
        <div class="col-sm-8 col-md-9">
        <ul style="list-style-type: none;">
            <li>Software development section manager</li>
            <li>CP Leadership Institute
                <ul>
                    <li>Transform offline business processes to online solution.</li>
                    <li>Review ,design, implement and customize both software and database design</li>
                    <li>In charge of software development projects management, coordinator outsourcing vendors</li>
                    <li>Contribute to all phases of the development life cycle</li>
                    <li>Summarized and reported directed to manager</li>
                </ul>
            </li>
            <li>Responsible to projects
                <ul>
                    <li>Operation system</li>
                    <li>Online registration with APIs</li>
                    <li>Program and Participant management</li>
                    <li>Facilities management</li>
                    <li>360 evaluation forms and reports</li>
                    <li>Financial system and report (E-invoice)</li>
                </ul>
            </li>
        </ul>
        </div>
    </div>
    <div class="row py-1">
        <div class="col-sm-4 col-md-3">JULY 2015 – JULY 2017</div>
        <div class="col-sm-8 col-md-9">
        <ul style="list-style-type: none;">
            <li>Software developer</li>
            <li>Asiasoft Corporation Public Company Limited
                <ul>
                    <li>Research ,develop and deliver software to support business and givenrequirements.</li>
                    <li>Review, analyze and modify existing parts of program, including encoding, testing, debugging and documentation.</li>
                    <li>Analyst system requirement or Analyst System improvement possibility.</li>
                    <li>Work with Technology team to design and build a maintainable technology infrastructure including build & testing environment.</li>
                    <li>Contribute to designing and building production systems on both web and mobile services.</li>
                    <li>Develop and perform test scenarios, test cases and test plan.</li>
                    <li>Perform work based on defined process and provide feedback on process improvements as appropriate.</li>
                </ul>
            </li>
            <li>Responsible to projects
                <ul>
                    <li>Refill Payment Gateway (Top-up) connect with other merchants payment services (such as Line Pay, KBank, Paypal, Indomog, MogPay, Gudang Voucher, Modern pay and OpenBucks)</li>
                    <li>Game Refill Center System</li>
                    <li>@Key system (Login with Digipass System for game member and internal user)</li>
                    <li>Customer Relationship Management System (Internal Admin Tool)</li>
                    <li>Navision/Financial Report</li>
                    <li>Customer Tracking Report System</li>
                    <li>Game Events, Ads banner system</li>
                </ul>
            </li>
        </ul>
                
        </div>
    </div>
     <hr/>
    <div class="row py-1">
        <div class="col-sm-4 col-md-3"></div>
        <div class="col-sm-8 col-md-9"></div>
    </div>
</div>


<?php
include_once('footer.phtml');
?>
