
<?php
include_once('header.phtml');    
?>
<div class="container" style="margin-top:10px;margin-bottom:10px;">
	<div>
      <!--   <p>Find X, Y, Z from  <?=$this->settext;?></p>
         <p>>> <?=$this->foundtext;?></p> -->

         <form class="navbar-form navbar-left" action="?act=find" method="post">
             <p>X, 5, 9, 15, 23, Y, Z</p>
                    <div class="form-inline pb-3">
                        <input type="text" class="form-control" placeholder="text X, 5, 9, 15, 23, Y, Z" name="text" value="" required autofocus>
                        <span class="glyphicon glyphicon-envelope form-control-feedback"> <?=$this->foundtext;?> </span>
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                </form>
         <hr/>
        <h4>xyz from vue</h4>
        <div id="app">
        <div class="wrapper">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-inline pb-3">
                    <input type="text" class="form-control" placeholder="text X, 5, 9, 15, 23, Y, Z" name="text" value="X, 5, 9, 15, 23, Y, Z" v-on:keyup="findXYZ($event)" required autofocus>
            </div>
                </div>
                <div class="col-md-6">
                    <div class="row" v-if='showx'>found X !</div>
                    <div class="row" v-if='showy'>found Y !</div>
                    <div class="row" v-if='showz'>found Z !</div>
                </div>
            </div>
            
           
        </div>
      </div>
	</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script>
var app = new Vue({
el: '#app',
data: {
    iText:'',
    showx:true,
    showy:true,
    showz:true
},
methods:{
    findXYZ: function(event){
        this.showx = (event.target.value.toUpperCase().includes("X")) ? true : false;
        this.showy = (event.target.value.toUpperCase().includes("Y")) ? true : false;
        this.showz = (event.target.value.toUpperCase().includes("Z")) ? true : false;
    }
}
});
</script>
<?php
include_once('footer.phtml');
?>
