
<?php
include_once('header.phtml');    
?>
<div class="container" style="margin-top:10px;">
	<div>
		<h1><?=$this->translate('hello');?>, find.phtml !</h1>
		
         <p>Find X, Y, Z from  <?=$this->settext;?></p>
         <p>>> <?=$this->foundtext;?></p>
        <hr/>
        <p> Please use “Place search|Place API(by Google)” for finding all restaurants in Bangsue area and show result by JSON</p>
        
                        <?php
                        $foundPlace = $this->foundPlace;
                        if(!empty($foundPlace['results'][0])){ 
                            $count = count($foundPlace['results']);
                           foreach($foundPlace['results'] as $key=>$value){  
                        ?>
                            <div class="row">
                                <div class="col-12 col-sm-12 col-md-12">
                                        <div class="row pt-3 pb-3">
                                            <div class="col-4 col-sm-4 col-md-4"> 
                                              <p class="title-column-right">  <?=$value->name;?></p>  
                                            </div>
                                            <div class="col-8 col-sm-8 col-md-8 pl-0">
                                                <p class="title-column-right">
                                                     <?=$value->formatted_address;?>
                                                </p>  
                                                <p class="text-column-right"> 
                                                <?php if(!empty($value->opening_hours->open_now)){
                                                    echo ($value->opening_hours->open_now == 1)?'Open Now !':'Closed';
                                                }
                                                else{
                                                    echo '-';
                                                }
                                                ?></p>
                                            </div>
                                        </div>
                                   
                                </div>
                            </div>
                        <?php
                           }
                            if(!empty($foundPlace['next_page_token']))
                            {
                                //next page
                                
                            }
                        }
                        ?>
	</div>
</div>
<?php
include_once('footer.phtml');
?>
