<?php
include_once('header.phtml');    
?>
<div class="container" style="margin-top:10px;">
   <div class="row">
       
       
    <div class="panel panel-default">
            <div class="panel-heading">Msg</div>
            <!-- Table -->
            <table class="table" style="width:100%;">
                <tr>
                    <td>#</td>
                    <td>Msg</td>
                    <td>URL</td>
                    <td>image url</td>
                  <!--   <td>Create by</td>
                    <td>createdate</td>
                    <td>Update By</td>
                    <td>Last update</td>-->
                    <td></td>
                    <td></td>
                </tr>
                <?php foreach ($this->data as $key=>$value) { ?>
                    <tr>
                        <td><?=$key+1;?></td>
                        <td><?=$value['line_msg'];?></td>
                        <td><a href="<?=$value['url'];?>" target="_blank">preview</a></td>
                        <td><img src="<?=$value['imageurl'];?>" style="max-width:100px;" /></td>
                       <!-- <td><?=$value['createby'];?></td>
                        <td><?=$value['createdate'];?></td>
                        <td><?=$value['updateby'];?></td>
                        <td><?=$value['lastupdate'];?></td> -->
                        <td>
                            <a class="btn fas fa-edit" href="<?php echo $this->url('scghome').$this->lang; ?>/line/<?=$value['line_msgid'];?>/?act=detail" title="edit"></a>
                        </td>
                        <td>
                            <a class="btn fas fa-paper-plane" href="<?php echo $this->url('scghome').$this->lang; ?>/line/<?=$value['line_msgid'];?>/?act=send" title="send"></a>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
    </div> 
<?php if($this->detail){ ?>
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Msg</div>
                <form class="navbar-form navbar-left" action="?act=edit" method="post">
                    <div class="form-inline">
                        <input type="hidden" name="line_msgid" value="<?=$this->detail['line_msgid']; ?>">
                        <input type="text" class="form-control" placeholder="Msg" name="line_msg" value="<?=$this->detail['line_msg']; ?>" required autofocus>
                        <input type="text" class="form-control" placeholder="URL" name="url" value="<?=$this->detail['url']; ?>" required autofocus>
                        <input type="text" class="form-control" placeholder="image URL" name="imageurl" value="<?=$this->detail['imageurl']; ?>" required autofocus>
                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>
    <?php } ?>
    <div>
       <!-- <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">Add New Msg</div>
                <form class="navbar-form navbar-left" action="?act=add" method="post">

                    <div class="form-inline">
                        <input type="text" class="form-control" placeholder="Name" name="name" required autofocus>
                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                        <button type="submit" class="btn btn-primary btn-l">Add</button>
                    </div>
                    
               
                </form>
            </div>
        </div> -->
	</div>
</div>
<?php
include_once('footer.phtml');
?>
