<?php
include_once('header.phtml');    
?>

<div class="container" style="margin-top:10px;">
   <div class="row">
       
 
            <div class="panel-heading">Message configuration</div>
         <hr/>
            <!-- Table -->
            <table class="table" style="width:100%;">
                <tr>
                    <td>#</td>
                    <td>Message</td>
                    <td>URL</td>
                    <td>Edit</td>
                     <!--<td>image url</td>
                    <td>Create by</td>
                    <td>createdate</td>
                    <td>Update By</td>
                    <td>Last update</td>-->
                    <td>Delete</td>
                </tr>
                <?php foreach ($this->data as $key=>$value) { ?>
                    <tr>
                        <td><?=$key+1;?></td>
                        <td><?=$value['line_msg'];?></td>
                        <td><a href="<?=$value['url'];?>" target="_blank">preview</a></td>
                        <!-- <td><img src="<?=$value['imageurl'];?>" style="max-width:100px;" /></td>
                       <td><?=$value['createby'];?></td>
                        <td><?=$value['createdate'];?></td>
                        <td><?=$value['updateby'];?></td>
                        <td><?=$value['lastupdate'];?></td> -->
                        <td>
                            <a class="btn fas fa-edit" href="<?php echo $this->url('scghome').$this->lang; ?>/line/<?=$value['line_msgid'];?>/?act=detail" title="edit"></a>
                        </td>
                        <td>
                            <a class="btn fas fa-trash-alt" href="<?php echo $this->url('scghome').$this->lang; ?>/line/<?=$value['line_msgid'];?>/?act=del" title="send"></a>
                        </td>
                    </tr>
                <?php } ?>
            </table>
       
    </div>
    <?php if($this->detail){ ?>
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Message</div>
                <hr/>
                <form class="navbar-form navbar-left" action="?act=edit" method="post">
                    <div class="form-inline">
                        <input type="hidden" name="line_msgid" value="<?=$this->detail['line_msgid']; ?>">
                        <div class="form-group" style="margin:15px">
                          <label>Message:</label>
                          <input type="text" class="form-control" placeholder="Message" name="line_msg" value="<?=$this->detail['line_msg']; ?>" required autofocus>
                        </div>
                        <div class="form-group" style="margin:15px">
                          <label>URL:</label>
                          <input type="text" class="form-control" placeholder="URL" name="url" value="<?=$this->detail['url']; ?>" required autofocus>
                        </div>
                        <button type="submit" class="btn btn-info btn-lg">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    <?php } ?>
    <div class="row">
        <?php echo $this->contentidx; ?>
        <div class="panel panel-default">
            <div class="panel-heading">Add Message </div>
            <hr/>
            <form class="navbar-form navbar-left" action="?act=add" method="post" id="my-form">
                <div class="form-inline">
<!--
                    <div class="form-group" style="margin:15px">
                      <label>Content type:</label>
                      <select class="form-control" id="contentid">
                        <option value="1">promotion</option>
                        <option value="2">event</option>
                        <option value="3">news</option>
                      </select>
                    </div>
-->
                    <div class="form-group" style="margin:15px">
                      <label>Message:</label>
                      <input type="text" class="form-control" placeholder="Message" name="line_msg" value="" required autofocus>
                    </div>
                    <div class="form-group" style="margin:15px">
                      <label>URL:</label>
                      <input type="text" class="form-control" placeholder="URL" name="url" value="" required autofocus>
                    </div>
                    <button type="submit" class="btn btn-info btn-lg">Submit</button>
                </div>
            </form>
        </div>
    </div>
    
</div>
<?php
include_once('footer.phtml');
?>
