<?php echo $this->doctype(); ?>
<html lang="en"> 
    <head>
        <META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=UTF-8">
        <meta http-equiv="Cache-control" content="public">
        <META HTTP-EQUIV="EXPIRES" CONTENT="<?php echo gmdate("D, d M Y H:i:s", time() + (60*60)) . " GMT"; ?>">
        <meta http-equiv="cleartype" content="on">
        <meta name="MobileOptimized" content="767">
        <meta name="HandheldFriendly" content="True">
        <meta name='mobile-web-app-capable' content='yes'>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable = no">
        <link rel="shortcut icon" href="<?php echo $this->url('home'); ?>img/favicon/s.ico" type="image/x-icon">
        <link rel="icon" href="<?php echo $this->url('home'); ?>img/favicon/s.ico" type="image/x-icon">
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->url('home'); ?>img/favicon/s.png">
        <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->url('home'); ?>img/favicon/s.png">
        <link rel="apple-touch-icon" sizes="57x57" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="<?php echo $this->url('home'); ?>img/favicon/favicon.ico">
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->url('home'); ?>img/favicon/s.ico">
        <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->url('home'); ?>img/favicon/s.ico">
        <link rel="icon" type="image/png" sizes="16x16" href="<?php echo $this->url('home'); ?>img/favicon/s.ico">
        <link rel="manifest" href="<?php echo $this->url('home'); ?>manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="<?php echo $this->url('home'); ?>img/icon/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
        <meta name='application-name' content='ZF3'>
	    <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name='apple-mobile-web-app-status-bar-style' content='black'>
        <meta name='apple-mobile-web-app-title' content='ZF3'>
	    <link rel="apple-touch-startup-image" href="<?php echo $this->url('home'); ?>img/icon/apple-icon-180x180.png">
	    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
            
        <META NAME="AUTHOR" CONTENT="Tonytoons">
            
        <META name="revisit-after" content="7 days">
        <META NAME="COPYRIGHT" CONTENT="&copy; <?php echo date('Y') ?> ZF3">
        <title><?php echo $this->translate('Sotha Back-end Assignment'); ?></title>
            
       <!-- Optional theme
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->
            
        <!-- Custom fonts for this theme -->
        <link href="<?php echo $this->url('home'); ?>vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

        <!-- Theme CSS -->
        <link href="<?php echo $this->url('home'); ?>css/freelancer.min.css" rel="stylesheet">
            
        <?php include_once 'css.phtml'; ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        
<script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <?php echo $this->content; ?>
        
        <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      -->
        
        <!-- Bootstrap core JavaScript -->
        <script src="<?php echo $this->url('home'); ?>vendor/jquery/jquery.min.js"></script>
        <script src="<?php echo $this->url('home'); ?>vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

        <!-- Plugin JavaScript -->
        <script src="<?php echo $this->url('home'); ?>vendor/jquery-easing/jquery.easing.min.js"></script>

        <!-- Contact Form JavaScript -->
        <script src="<?php echo $this->url('home'); ?>js/jqBootstrapValidation.js"></script>
        <script src="<?php echo $this->url('home'); ?>js/contact_me.js"></script>

        <!-- Custom scripts for this template -->
        <script src="<?php echo $this->url('home'); ?>js/freelancer.min.js"></script>
        <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.4.2/vue.min.js" defer></script> -->
        
        <script src="<?php echo $this->url('home'); ?>js/myJS.js" onLoad="init();" defer></script>
    </body>
</html>
<?php echo $this->inlineScript(); ?>